/**
 * Chat attachments: files uploaded by the operator or media generated by
 * skills. Binary content lives in the private 'attachments' storage bucket;
 * messages carry only this metadata in memories.metadata.attachments.
 */

export const ATTACHMENTS_BUCKET = 'attachments';

export type AttachmentKind = 'image' | 'audio' | 'video' | 'text' | 'file';

export interface Attachment {
  path: string;
  name: string;
  mime: string;
  size: number;
  kind: AttachmentKind;
}

const TEXT_EXTENSIONS = [
  'txt', 'md', 'markdown', 'csv', 'tsv', 'json', 'yaml', 'yml', 'xml', 'html',
  'css', 'js', 'jsx', 'ts', 'tsx', 'py', 'rb', 'go', 'rs', 'java', 'c', 'h',
  'cpp', 'cs', 'sh', 'sql', 'toml', 'ini', 'env', 'log',
];

export function isTextLike(mime: string, name: string): boolean {
  if (mime.startsWith('text/')) return true;
  if (['application/json', 'application/xml', 'application/x-yaml'].includes(mime)) return true;
  const ext = name.split('.').pop()?.toLowerCase() || '';
  return TEXT_EXTENSIONS.includes(ext);
}

export function attachmentKind(mime: string, name: string): AttachmentKind {
  if (mime.startsWith('image/')) return 'image';
  if (mime.startsWith('audio/')) return 'audio';
  if (mime.startsWith('video/')) return 'video';
  if (isTextLike(mime, name)) return 'text';
  return 'file';
}

export function safeStorageName(name: string): string {
  return name.replace(/[^a-zA-Z0-9._-]/g, '_').slice(-80);
}

export function formatBytes(size: number): string {
  if (size < 1024) return `${size}B`;
  if (size < 1024 * 1024) return `${(size / 1024).toFixed(1)}KB`;
  return `${(size / (1024 * 1024)).toFixed(1)}MB`;
}
